"""PROVIDER: exclusive, reversible transfer of Codex 0.159.3 local thread state.

The native paginated store cannot import an existing rollout into another home.
Unknown schemas stay local. The source is retained archived, never deleted.
"""
from contextlib import ExitStack, contextmanager, closing
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shutil
import sqlite3
import time
import uuid


class TransferError(RuntimeError):
    pass


# Generated by the installed 0.159.3 binary and checked against its tagged migrations.
SCHEMAS = {
    'goals_1.sqlite': '45e9b0a503ed1f8dae8f5dac22e47cb3f471c2a250db01f4b508b25bdd1b42cf',
    'memories_1.sqlite': '336cf750d54445731a85a98978c3ed856c3b4082cd78dedea1abd077ccaa3f78',
    'queue_1.sqlite': '61fa56e75e81b3877d41334e93680fa000821fad51cb23a6614cdd7559aa8749',
    'state_5.sqlite': '73bcf64ead533cff2e73e7049212d9793453a5830580295769669c55956b0d47',
    'thread_history_1.sqlite': 'a06ad45b4139c3e11664bb3930a0b9e2214fd623233f8bf5c13e1767d37c7f60',
}


def atomic_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + '.tmp')
    fd = os.open(temp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w') as file:
        json.dump(value, file)
        file.flush()
        os.fsync(file.fileno())
    os.replace(temp, path)
    fd = os.open(path.parent, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def schema(connection):
    return list(connection.execute("SELECT type,name,sql FROM sqlite_master WHERE sql IS NOT NULL "
                                   "AND name NOT LIKE 'sqlite_%' ORDER BY type,name"))


def file_hash(path):
    with Path(path).open('rb') as file:
        return hashlib.file_digest(file, 'sha256').hexdigest()


@contextmanager
def writers(home, ids):
    """Use Codex's own flock namespace; never interrupt an existing writer.

    Coordination protects lock-file creation from native stale-file cleanup. Keep
    thread locks until source archival commits, so a racing resume fails closed.
    """
    folder = Path(home) / 'thread-writer-locks'
    folder.mkdir(exist_ok=True)
    with ExitStack() as stack:
        coordination = stack.enter_context((folder / '.coordination.lock').open('a+'))
        try:
            fcntl.flock(coordination, fcntl.LOCK_EX | fcntl.LOCK_NB)
            for tid in sorted(ids):
                uuid.UUID(tid)
                file = stack.enter_context((folder / (tid + '.lock')).open('a+'))
                fcntl.flock(file, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise TransferError('Conversation still has a Codex writer; transfer waits until it closes') from error
        fcntl.flock(coordination, fcntl.LOCK_UN)
        yield
        # Leave the empty lock files: native cleanup removes them under coordination.


def family(connection, tid):
    ids = {tid}
    edges = list(connection.execute('SELECT parent_thread_id,child_thread_id FROM thread_spawn_edges'))
    while True:
        expanded = ids | {child for parent, child in edges if parent in ids}
        if expanded == ids:
            return ids
        ids = expanded


def transfer(source, destination, tid):
    """Called only before an owned daemon starts. Return the authoritative home.

    A prepared journal recovers the one crash boundary between the archive commit
    and publication. Neither an accepted queue item nor a model turn is replayed.
    """
    source, destination = Path(source).resolve(), Path(destination).resolve()
    journal_path = destination / 'colony-transfer.json'
    journal = json.loads(journal_path.read_text()) if journal_path.exists() else {}
    if journal.get('state') == 'published':
        if journal['thread'] != tid:
            raise TransferError('This home already belongs to another conversation')
        return destination
    if journal and (journal.get('thread') != tid or journal.get('source') != str(source)):
        raise TransferError('An unfinished transfer belongs to a different conversation')
    state_path = source / 'state_5.sqlite'
    if not state_path.exists():
        raise TransferError('Codex has not indexed this conversation; keeping its original home')
    with closing(sqlite3.connect(f'file:{state_path}?mode=ro', uri=True)) as state:
        ids = family(state, tid)
    with writers(source, ids), ExitStack() as stack:
        databases = {}
        for name in SCHEMAS:
            path = source / name
            if not path.exists():
                continue
            connection = stack.enter_context(closing(sqlite3.connect(f'file:{path}?mode=ro', uri=True)))
            connection.execute('BEGIN')
            definitions = schema(connection)
            digest = hashlib.sha256(json.dumps(definitions).encode()).hexdigest()
            if digest != SCHEMAS[name]:
                raise TransferError(f'Unsupported Codex schema in {name}; original conversation kept local')
            databases[name] = (connection, definitions)
        state = databases['state_5.sqlite'][0]
        if family(state, tid) != ids:
            raise TransferError('Conversation family changed; transfer deferred')
        marks = ','.join('?' for _ in ids)
        state.row_factory = sqlite3.Row
        rows = [dict(r) for r in state.execute(f'SELECT * FROM threads WHERE id IN ({marks})', sorted(ids))]
        state.row_factory = None
        root = next((r for r in rows if r['id'] == tid), None)
        if not root or len(rows) != len(ids):
            raise TransferError('Conversation family is incomplete; keeping its original home')
        if journal.get('state') == 'prepared':
            if root['archived']:
                if not journal.get('files') or any(not (destination / p).is_file() or file_hash(destination / p) != digest
                                                   for p, digest in journal['files'].items()):
                    raise TransferError('Prepared transfer is incomplete; source archive retained for recovery')
                journal['state'] = 'published'
                atomic_json(journal_path, journal)
                return destination
            # A previous attempt prepared a valid copy but had not archived the source.
            # Recopy under current writer locks; no destination has run yet.
        elif root['archived']:
            raise TransferError('Source conversation is already archived')
        destination.mkdir(parents=True, exist_ok=True, mode=0o700)
        for r in rows:
            path = Path(r['rollout_path'])
            try:
                relative = path.relative_to(source)
            except ValueError as error:
                raise TransferError('Conversation references history outside its source home') from error
            if not path.is_file():
                raise TransferError('A conversation history file is missing')
            # Forks may read ancestor segments outside the spawn family. Until native
            # transfer supports these, do not pretend the visible transcript is complete.
            with path.open() as file:
                first = json.loads(file.readline())
            meta = first.get('payload', {})
            if meta.get('id') != r['id']:
                raise TransferError('History does not match its indexed conversation')
            if meta.get('forked_from_id') or meta.get('forked_from'):
                raise TransferError('Forked history needs native transfer support; conversation kept local')
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
            os.chmod(target, 0o600)
        sections = {r['thread_section_id'] for r in rows if r['thread_section_id']}
        projects = {r['project_id'] for r in rows if r['project_id']}
        for name, (connection, definitions) in databases.items():
            target = destination / name
            target.unlink(missing_ok=True)
            for suffix in ('-wal', '-shm'):
                target.with_name(target.name + suffix).unlink(missing_ok=True)
            with closing(sqlite3.connect(target)) as out, out:
                for kind, table, sql in sorted(definitions, key=lambda d: d[0] != 'table'):
                    out.execute(sql)
                for kind, table, _ in definitions:
                    if kind != 'table':
                        continue
                    columns = [r[1] for r in connection.execute(f'PRAGMA table_info("{table}")')]
                    if table == '_sqlx_migrations':
                        selected = list(connection.execute(f'SELECT * FROM "{table}"'))
                    elif table == 'threads':
                        selected = list(connection.execute(f'SELECT * FROM threads WHERE id IN ({marks})', sorted(ids)))
                    elif 'thread_id' in columns:
                        selected = list(connection.execute(f'SELECT * FROM "{table}" WHERE thread_id IN ({marks})', sorted(ids)))
                    elif table == 'thread_spawn_edges':
                        selected = list(connection.execute(f'SELECT * FROM "{table}" WHERE parent_thread_id IN ({marks})', sorted(ids)))
                    elif table in ('projects', 'thread_sections', 'project_roots'):
                        values = sections if table == 'thread_sections' else projects
                        field = 'project_id' if table == 'project_roots' else 'id'
                        selected = [r for r in connection.execute(f'SELECT * FROM "{table}"') if r[columns.index(field)] in values]
                    else:
                        continue                 # no credentials, enrollments, unrelated threads or global jobs
                    if table == 'threads':
                        pos = columns.index('rollout_path')
                        selected = [tuple(str(destination / Path(v).relative_to(source)) if i == pos else v
                                          for i, v in enumerate(row)) for row in selected]
                    if selected:
                        out.executemany(f'INSERT INTO "{table}" VALUES ({",".join("?" for _ in columns)})', selected)
                if out.execute('PRAGMA integrity_check').fetchone()[0] != 'ok':
                    raise TransferError('Transferred Codex state failed its integrity check')
            os.chmod(target, 0o600)
        copied = [destination / name for name in databases]
        copied += [destination / Path(r['rollout_path']).relative_to(source) for r in rows]
        for path in copied:
            with path.open('rb') as file:
                os.fsync(file.fileno())
        journal = dict(source=str(source), thread=tid, family=sorted(ids), state='prepared',
                       files={str(p.relative_to(destination)): file_hash(p) for p in copied})
        atomic_json(journal_path, journal)
        # Native writer locks exclude old TUI/app writers. Archive in one transaction
        # before publishing: retaining an unarchived duplicate would split ownership.
        # Only the two native archive fields change; original history stays untouched.
        for connection, _ in databases.values():
            connection.rollback()
        with closing(sqlite3.connect(state_path)) as writable, writable:
            writable.execute(f'UPDATE threads SET archived=1,archived_at=? WHERE id IN ({marks})',
                             [int(time.time()), *sorted(ids)])
        journal['state'] = 'published'
        atomic_json(journal_path, journal)
    return destination
